"use client";

import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { ShieldAlert } from "lucide-react";
import { useAIConsent } from "@/hooks/use-ai-consent";

interface AIConsentDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  /** Called after the user grants consent */
  onConsented?: () => void;
}

/**
 * Consent dialog shown before any AI coaching request.
 * Explains that performance data will be sent to a third-party LLM provider
 * (potentially outside the EU). The user can accept once (session) or
 * permanently (localStorage).
 */
export function AIConsentDialog({
  open,
  onOpenChange,
  onConsented,
}: AIConsentDialogProps) {
  const { grant } = useAIConsent();

  function handleAccept() {
    grant();
    onOpenChange(false);
    onConsented?.();
  }

  function handleDecline() {
    onOpenChange(false);
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent showCloseButton={false} className="max-w-md">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <ShieldAlert className="w-5 h-5 text-muted-foreground shrink-0" aria-hidden="true" />
            AI data processing
          </DialogTitle>
          <DialogDescription>
            Before using AI coaching, please review how your data is processed.
          </DialogDescription>
        </DialogHeader>

        <div className="text-sm text-muted-foreground space-y-2">
          <p>
            AI coaching tips are generated by a third-party language model.
            To generate a tip, the following data is sent to the AI provider:
          </p>
          <ul className="list-disc pl-5 space-y-0.5">
            <li>Competitor name, division, and club</li>
            <li>Match name and stage details</li>
            <li>Hit factors, zone counts, and penalty statistics</li>
          </ul>
          <p>
            This data may be processed on servers outside the EU/EEA
            (e.g. in the United States). The AI provider may retain data
            according to its own policies.
          </p>
          <p>
            All competition results used are publicly available on
            shootnscoreit.com.
          </p>
        </div>

        <DialogFooter className="flex-col gap-2 sm:flex-row">
          <Button variant="outline" onClick={handleDecline}>
            Decline
          </Button>
          <Button onClick={handleAccept}>
            Accept and continue
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
